swagger: '2.0'
info:
  description:  Documentação das requisições disponiveis da diversamente-api https://diversamente-api.herokuapp.com/api/cards/
  version: 1.0.0
  title: DiversaMente API
  contact:
    email: darajsv@gmail.com
basePath: /api
tags:
- name: Cartas
  description: Requisições disponiveis para as cartas do jogo
- name: Auth
  description: Autenticação para fazer algumas requisições

paths:
  /auth/login:
    post:
      tags: 
      - Auth
      summary: Faz Login para fazer requisições de editar/atualizar/excluir
      operationId: login
      consumes:
      - application/json
      produces:
      - application/json
      parameters: 
      - in: body
        name: CardRequest
        schema:
          $ref: '#/definitions/LoginRequest'
      responses: 
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/LoginResponse'
        400:
          description: invalid password
        500:
          description: internal server error

  /list:
    get:
      tags:
      - Cartas
      summary: Lista todas as cartas do jogo
      operationId: listCards
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/CardResponse'
        500:
          description: internal server error
  /list/{id}:
    get:
      tags:
      - Cartas
      summary: Busca uma carta pelo o ID
      operationId: listById
      produces: 
      - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items: 
              $ref: '#/definitions/CardResponse'
        500:
          description: internal server error        
  /dashboard/cards/create:
    post:
      tags:
      - Cartas
      summary: Adiciona uma nova Carta
      operationId: addCard
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: CardRequest
        schema:
          $ref: '#/definitions/CardRequest'
      responses:
        201:
          description: item created
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists
  /dashboard/cards/edit/{id}:
    put:
      tags:
      - Cartas
      summary: Edita a carta pelo o ID
      operationId: updateCard
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: CardRequest
        schema:
          $ref: '#/definitions/CardRequest'
      responses:
        200:
          description: item updated
          schema:
            type: array
            items:
              $ref: '#/definitions/CardResponse'
        400:
          description: invalid input, object invalid
        404:
          description: not found
        500:
          description: internal server error
  /dasboard/cards/delete/{id}:
    delete:
      tags:
      - Cartas
      summary: Exclui uma carta pelo o ID
      operationId: deleteById
      produces: 
      - application/json
      responses:
        200:
          description: OK
        404:
          description: not found
        500:
          description: internal server error       
definitions:
  CardResponse:
    type: object
    properties:
      id:
        type: string
        example: 2
      name:
        type: string
        example: Homem Trans
      description:
        type: string
        example: Homem trans, transgênero, ou transexual é um homem que foi designado ao sexo feminino quando nasceu, contudo, este se atribui ao gênero masculino. O momento em que um homem trans descobre a sua identificação como do gênero masculino varia e não há narrativa única, podendo ser desde na primeira infância até depois de adulto.
      image:
        type: string
        example: gs://diversamentedb.appspot.com
      createdAt: 
        type: string
        example: "2021-05-23T00:40:30.668Z"
      updatedAt:
        type: string
        example: "2021-05-23T00:40:30.668Z"
  CardRequest:
    type: object
    properties:
      name:
        type: string
        example: Homem Trans
      description:
        type: string
        example: Homem trans, transgênero, ou transexual é um homem que foi designado ao sexo feminino quando nasceu, contudo, este se atribui ao gênero masculino. O momento em que um homem trans descobre a sua identificação como do gênero masculino varia e não há narrativa única, podendo ser desde na primeira infância até depois de adulto.
      image:
        type: string
        example: gs://diversamentedb.appspot.com
  LoginRequest:
      type: object
      properties:
        email:
          type: string
          example: admin@diversamente.com
        password: 
          type: string
          example: minhaSenha
  LoginResponse:
    type: object
    properties: 
      email: 
        type: string
        example: admin@diversamente.com
      token: 
        type: string
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBkaXZlcnNhbWVudGUuY29tIiwiaWF0IjoxNjIyMTM5NTMxfQ.aoX3m25fOrIeLK-nQojQoO4lrH91E7uPxNKAW6Uw

schemes:
 - https
